### ISSUE TITLE
Cr Api Config Clan Help

### ISSUE THREAD

**Issue by Blessedville** [cr-api/cr-api#119]
Trying to get my clan family on cr api

**Comment by smlbiobot** [comment]
Please see https://github.com/cr-api/cr-api/wiki/Family-Config for how to configure your clan and send me the full YAML config.

**Comment by smlbiobot** [comment]
@Blessedville Any progress on this? I haven’t heard back from you for two days.

**Comment by Blesedville** [comment]
Trying to find A YAML to type it

**Comment by smlbiobot** [comment]
YAML is just a text file. Just copy the config from the wiki above and type it.

**Comment by Blesedville** [comment]
Oh ok

**Comment by Blesedville** [comment]
Let me finish typing it upand I'll send it your way.

**Comment by Blesedville** [comment]
Where do i find a YAML file

**Comment by Gr8z** [comment]
Go to the examples section and copy the code. Then modify it with your own clan family in notepad, then send it here in this issue.

**Comment by Blesedville** [comment]
ok

**Comment by Blesedville** [comment]
where do i find the elixir with black background emblems

**Comment by Blesedville** [comment]
name: UnderWorld Clan Family
key: uwrl
color: purple
emblem: Elixir_02
info:
  logo: https://imgur.com/a/pMHhr
  description: >
    The ** UnderWorld Clan Family** (UWRL) consists of 8 trophy-pushing clans.

    UnderWorld clan family consists of the following below:
      League Connections: 100 + Challenger and Master throughout the 8 UnderWorld clans
      Play Hours: We have members in game and in our external chat around the clock.
      Geography: We have members from 28 countries and 6 continents 
      Chat: Discord Based Clan and Community chat areas.
      Focus: Friendly competition and sharing/advise so we can continue to improve.
social:
  -twitter: https://twitter.com/underworldcr?lang=en
  -discord: https://discord.gg/g4kfV4R
  -youtube: https://t.co/OYhux7oPyh
clans:
  -name: UW eSports
  -tag: 8VJCQPQ9
  -name: UNDERATED
  -tag: 222VGJ
  -name: Underbelly
  -tag: 2J8UVG99
  -name: Undertake
  -tag: PY9UY9L
  -name: UnderMayhem
  -tag: 8P9QQCCR
  -name: UnderCarnage
  -tag: 2JRU00JL
  -name: UnderCooked
  -tag: 8RYGR9PJ
  -name: Underminers
  -tag: 2UV822J0

**Comment by Blesedville** [comment]
i cant put it on git hub

**Comment by smlbiobot** [comment]
Escape it

**Comment by smlbiobot** [comment]
You have escaped your description why not the whole thing?

**Comment by smlbiobot** [comment]
You can't have markdown escapes quotes in description. Please reformat description into paragraphs

**Comment by Blesedville** [comment]
what do you mean escape?

**Comment by smlbiobot** [comment]
Implemented: http://cr-api.com/clan/family/uwrl

Please check. Description cannot have blockquotes nor bullet points. I have re-formatted for you like this:

```yaml
  - name: UnderWorld Clan Family
    key: uwrl
    color: purple
    emblem: Elixir_02
    info:
      logo: /static/img/brands/logo/uwrl.jpg
      description: >
        The **UnderWorld Clan Family** (UWRL) consists of 8 trophy-pushing clans.


        UnderWorld clan family consists of the following:
        **League Connections:** 100 + Challenger and Master throughout the 8 UnderWorld clans.
        **Play Hours:** We have members in game and in our external chat around the clock.
        **Geography:** We have members from 28 countries and 6 continents.
        **Chat:** Discord Based Clan and Community chat areas.
        **Focus:** Friendly competition and sharing/advise so we can continue to improve.
      social:
        - twitter: https://twitter.com/underworldcr?lang=en
        - discord: https://discord.gg/g4kfV4R
        - youtube: https://www.youtube.com/channel/UCnivB1vhI0smz_oz6Ow7FPw
    clans:
      - name: UW eSports
        tag: 8VJCQPQ9
      - name: UNDERATED
        tag: 222VGJ
      - name: Underbelly
        tag: 2J8UVG99
      - name: Undertake
        tag: PY9UY9L
      - name: UnderMayhem
        tag: 8P9QQCCR
      - name: UnderCarnage
        tag: 2JRU00JL
      - name: UnderCooked
        tag: 8RYGR9PJ
      - name: Underminers
        tag: 2UV822J0
```

If you don’t like it, please tweak and repost.
