### ISSUE TITLE
Clan Family Update

### ISSUE THREAD

**Issue by TheZeny** [cr-api/cr-api#149]
```yaml 
- name: Elementar Bananen
    key: banana
    color: Yellow
    emblem: flag_j_03.png
    sort: trophy
    info:
      logo: comming soon...
      description: >
        Die **Elementar Bananen** Familie besteht aus aktuell 14 Clans
        und ist damit die größte Clash Royale Familie im deutschsprachigen Raum.
        Drei unserer Clans sind **Top Lokal** und weitere werden folgen.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        **Aktivität** zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität 
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
    clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Krypton Bananen
        tag: 990JPUP2
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Brom Bananen
        tag: 8Y9U8R2G
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Dubnium Bananen
        tag: 92JRUYC8
```

**Comment by smlbiobot** [comment]
Re-opening…

**Comment by smlbiobot** [comment]
@TheZeny in the future add the three backticks followed by yaml, then end the config with another three backticks to escape the code so they will be formatted. I have updated above, see screenshot below:

<img width="273" alt="screen shot 2017-12-30 at 3 23 19 pm" src="https://user-images.githubusercontent.com/25040297/34452216-6faecfde-ed75-11e7-87d2-e65cd7d9ab9d.png">

**Comment by smlbiobot** [comment]
This is the updated sanitized config, please save it for future reference:

```yaml
  - name: Elementar Bananen
    key: banana
    color: yellow
    emblem: flag_j_03
    sort: trophy
    track: false
    info:
      description: >
        Die **Elementar Bananen** Familie besteht aus aktuell 14 Clans
        und ist damit die größte Clash Royale Familie im deutschsprachigen Raum.
        Drei unserer Clans sind **Top Lokal** und weitere werden folgen.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        **Aktivität** zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
    clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Krypton Bananen
        tag: 990JPUP2
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Brom Bananen
        tag: 8Y9U8R2G
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Dubnium Bananen
        tag: 92JRUYC8
```
