### ISSUE TITLE
Reddit Hotel Clan Family

### ISSUE THREAD

**Issue by pabgar6** [cr-api/cr-api#154]
```
 - name: Reddit Hotel Clan Family
    key: hotel
    color: blue
    emblem: Tower_03
    info:
      description: >
      	In the early days of the Clash Royale soft launch, Daner and friends decided to open the doors to the **Reddit Hotel Clan family** to everybody. The clan family has grown from a humble Hotel, into a Clan system including Unity, Motel, Hostel and Inn. The momentum hasn't stopped as we develop into one of the leading forces of the Reddit Clan System! As we continue to grow, we open our doors to anybody who is determined and willing to join in the momentum as we aim for the top.
	
	Want to learn more about us? Join our Discord server linked below!
 
      social:

        - discord: https://discord.me/reddit_hotel

    clans:
      - name: Reddit Hotel
        tag: 8PVJ0P
      - name: Reddit Unity
        tag: 92RP0
      - name: Reddit Motel
        tag: 8JVC90Q8
      - name: Reddit Hostel
        tag: 2L88Y0UY
      - name: Reddit Inn
        tag: J0GG0G0
 ```

**Comment by smlbiobot** [comment]
🤔

**Comment by pabgar6** [comment]
👀

**Comment by smlbiobot** [comment]
Please save the following sanitized config for your records:

```yaml
  - name: Reddit Hotel Clan Family
    key: hotel
    color: blue
    emblem: Tower_03
    info:
      description: >
        In the early days of the Clash Royale soft launch,
        Daner and friends decided to open the doors to the **Reddit Hotel Clan family** to everybody.
        The clan family has grown from a humble Hotel,
        into a Clan system including Unity, Motel, Hostel and Inn.
        The momentum hasn't stopped as we develop into one of the leading
        forces of the Reddit Clan System! As we continue to grow, we open our doors
        to anybody who is determined and willing to join in the momentum as we aim for the top.


        Want to learn more about us? Join our Discord server linked below!
      social:
        - discord: https://discord.me/reddit_hotel
    clans:
      - name: Reddit Hotel
        tag: 8PVJ0P
      - name: Reddit Unity
        tag: 92RP0
      - name: Reddit Motel
        tag: 8JVC90Q8
      - name: Reddit Hostel
        tag: 2L88Y0UY
      - name: Reddit Inn
        tag: J0GG0G0
```

Important: in the future, please don’t use `TAB` for indentation. Use `SPACE` instead. Also, your copy is very long and on mobile devices, people won’t see any of your clans on page 1.

**Comment by smlbiobot** [comment]
Implemented: http://cr-api.com/clan/family/hotel

**Comment by pabgar6** [comment]
```yaml
  - name: Reddit Hotel Clan Family
    key: hotel
    color: blue
    emblem: Tower_03
    info:
      description: >
        In the early days of the Clash Royale soft launch,
        Daner and friends decided to open the doors 
        to the **Reddit Hotel Clan family** to everybody.
        The clan family has grown from a humble Hotel,
        into a Clan system including Unity, Motel, Hostel and Inn.
        The momentum hasn't stopped as we develop into one of the leading
        forces of the Reddit Clan System! As we continue to grow, we open our doors
        to anybody who is determined and willing to 
        join in the momentum as we aim for the top.


        Want to learn more about us? Join our Discord server linked below!
      social:
        - discord: https://discord.me/reddit_hotel
    clans:
      - name: Reddit Hotel
        tag: 8PVJ0P
      - name: Reddit Unity
        tag: 92RP0
      - name: Reddit Motel
        tag: 8JVC90Q8
      - name: Reddit Hostel
        tag: 2L88Y0UY
      - name: Reddit Inn
        tag: J0GG0G0
      - name: Reddit Warriors
        tag: CG9Y8
```

**Comment by smlbiobot** [comment]
Please edit this config in the future:

```yaml
  - name: Reddit Hotel Clan Family
    key: hotel
    color: blue
    emblem: Tower_03
    track: false
    feature: true
    info:
      description: >
        In the early days of the Clash Royale soft launch,
        Daner and friends decided to open the doors
        to the **Reddit Hotel Clan family** to everybody.
        The clan family has grown from a humble Hotel,
        into a Clan system including Unity, Motel, Hostel and Inn.
        The momentum hasn't stopped as we develop into one of the leading
        forces of the Reddit Clan System! As we continue to grow, we open our doors
        to anybody who is determined and willing to
        join in the momentum as we aim for the top.


        Want to learn more about us? Join our Discord server linked below!
      social:
        - discord: https://discord.me/reddit_hotel
    clans:
      - name: Reddit Hotel
        tag: 8PVJ0P
      - name: Reddit Unity
        tag: 92RP0
      - name: Reddit Motel
        tag: 8JVC90Q8
      - name: Reddit Hostel
        tag: 2L88Y0UY
      - name: Reddit Inn
        tag: J0GG0G0
      - name: Reddit Warriors
        tag: CG9Y8
```
