### ISSUE TITLE
Update Level One Family Clans Request

### ISSUE THREAD

**Issue by Otche-Nova** [cr-api/cr-api#155]
## Request Details:

```yaml
  - name: Level One
    key: one
    color: purple
    emblem: Star_Shine_03
    track: false
    sort: trophy
    clans:
      - name: Nova I One
        tag: 92VJGGRJ
      - name: Nova I Two
        tag: 8JU9UYGU
      - name: Nova I Three
        tag: 90Q0YJL2
      - name: Nova I Four
        tag: 90GJUUPC
      - name: Nova I Five
        tag: 8CGQ8RJR
      - name: Nova I Six
        tag: 9PCCL022
      - name: FA Level 1!
        tag: 2R8Q9QJ0
      - name: FA Level 1 too!
        tag: 2CJJ9YGU
      - name: FA Level 1 (3)
        tag: 888GYJ9J
      - name: Os Gemadinhos
        tag: 88C0YPLG
      - name: level one
        tag: 88RQ92QR
      - name: Lvl 1
        tag: 2R9J8VCY
      - name: 1 lvl
        tag: 2JPUPQJG
      - name: lvl 1 only
        tag: 89V8C9UC
      - name: lvl 1 beat down
        tag: 2LUU2LCG
      - name: LvL 1
        tag: 2RGUPQY9
      - name: lvl 1
        tag: 2GC99VJV
      - name: Liberty Level 1
        tag: 88JRJCCY
      - name: 别小看一级玩家
        tag: 2LRCL2JY
      - name: The First
        tag: 82VVYV8Q
```

```
GET
http://api.cr-api.com/top/clans
```

## Response Details:

```
Code: 200

[...]

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):
