### ISSUE TITLE
Family Update - Notorious

### ISSUE THREAD

**Issue by Lekic** [cr-api/cr-api#163]
```yaml
- name: Notorious
  key: notorious
  color: red
  emblem: Tower_02
  sort: trophy
  info:
    logo: https://www.dropbox.com/s/50pfm0anz5brxoo/notorious.png?dl=0
    description: >
      **Notorious** is a global mobile gaming organisation focused on providing
      players with a place they can reach their full potential. We treat our members
      as a family collective, supporting each other in any ventures and endeavours they
      wish to pursuit.

      The Notorious family boasts over 50 Clash Royale clans in over 20 regions. Our flagship,
      international clan is a top 10 finisher, with many of our regional clans finishing top 3 in
      their respective regions. Our regional clans have a feeder system to help players grow, while
      still having a home on the way up. We also have a competitive and pro team who frequently
      represent us in various leagues across the globe.

      We offer something for everybody, constantly rewarding members for excellent performance in
      both ladder pushing and competitive play. We do this to ensure all of our family members
      enjoy being part of the family and **#StayNotorious**!
    social:
      - website: https:/notorious.gg
      - discord: http://discord.gg/j5bMZaG
      - twitter: https://twitter.com/NotoriousRoyale
      - facebook: https://facebook.com/NotoriousRoyale
      - twitch: https://twitch.tv/NotoriousRoyale
  clans:
    - name: Notorious
      tag: 2Q9RGGVV
    - name: Notorious AU
      tag: 8GPJVUJ2
    - name: Notorious CA
      tag: 8QYUJ8GU
    - name: Notorious IN
      tag: 8YGRGGQG
    - name: Notorious LA
      tag: 8L28U9C0
    - name: Notorious NA
      tag: 892YU99V
    - name: Notorious NZ
      tag: 8LJVJJ8J
    - name: Notorious NP
      tag: 8UQPGR2G
    - name: Notorious PL
      tag: 8QC8GQQP
    - name: Notorious PT
      tag: 8JVGLUPR
    - name: Notorious PW
      tag: 8U220LJ2
    - name: Notorious RSA
      tag: 9PU0LGV8
    - name: Notorious RU
      tag: 8QUC2Q0J
    - name: Notorious UK
      tag: 8RQVJVVV
    - name: Notorious US
      tag: 8UU0VRGY
```
