### ISSUE TITLE
Clan family edit for Stu's Army!

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#166]
The gist has been updated with the new clan addition to the family:
https://gist.github.com/fourjr/a12bfaac6474cf73b86b9842465f09d3

**Comment by smlbiobot** [comment]
Can you tell me what’s changed instead of me trying to do the manual merge?

**Comment by smlbiobot** [comment]
Because I can’t really just copy and paste everything…

**Comment by smlbiobot** [comment]
Alternatively, can you keep everything I have here and then edit with the exact spacing + indentation I have in here:

```yaml
  - name: Stu's Army!
    key: stusarmy
    color: blue
    track: false
    emblem: Fugi_03
    feature: true
    info:
      logo: /static/img/brands/logo/stusarmy.webp
      description: >
        Stu’s Army is a **five clan family** that consists of all kinds of players,
        ranging from competitive, to casual! We even have an **eSports team** which you can find out more
        by joining our Discord Server linked below!

        We are constantly getting Tier 10 for our clan chests in all five of our clans
        and donations are getting filled as fast as possible!
      social:
        - discord: https://discord.gg/N2jS3cD
        - twitter: https://twitter.com/StusArmyCR
        - reddit: https://www.reddit.com/r/RoyaleRecruit/comments/7fnpqp/4000_3800_3000_2800_2400_
    clans:
      - name: Stu's Army!
        tag: 88PYQV
      - name: Stu's Army! II
        tag: 29UQQ282
      - name: Stu's Army! III
        tag: 28JU8P0Y
      - name: Stu's Army! IV
        tag: 8PUUGRYG
      - name: Stu's Army! V
        tag: 8YUU2CQV
```

For example: don’t use your logo link as we can’t serve images from everywhere.
