### ISSUE TITLE
Family Config: LeGeND Family

### ISSUE THREAD

**Issue by Gr8z** [cr-api/cr-api#170]
Hey, @smlbiobot Can you please share the YAML config for LeGeND. I have a few minor edits I need to make. I will also highlight what I changed.

**Comment by smlbiobot** [comment]
sure, please keep spacing (especially in front of the first line):

```yaml
  - name: LeGeND Family
    key: legend
    color: yellow
    track: false
    emblem: Flame_03
    feature: true
    info:
      logo: /static/img/brands/logo/legend.png
      description: >
        The Legend family is one of the oldest and biggest families in Clash Royale
        with our 600 members and 13 clans!
        Since creation, we as a family and individual players have grown immensely
        and continue to today.
        We believe that’s the reason why we have come so far.
        **The family is a place for everyone, as our members come from all around the world,
        from casual to competitive players, old to young,
        active to very active and so on.**
        We all share a fellow passion for the game, are friendly, always donate,
        help each other out with the same goal: to always improve our skills and have a great time!
        **Join the Family. Become a Legend. **
      social:
        - website: https://legendclans.com/
        - twitter: https://twitter.com/TheLegendClans
        - instagram: https://www.instagram.com/legendclans
        - facebook: https://www.facebook.com/LegendClans
        - discord: https://discord.me/legendfamily
        - email: mailto:board@legendclans.com
    clans:
      - name: Dragons Eight
        tag: 29YPJYY
      - name: LeGeND eSports!
        tag: 2GJYVRYQ
      - name: LeGeND Squad!
        tag: 80CC8
      - name: Dragons Eight 2
        tag: Y8G9C09
      - name: LeGeND Prime!
        tag: 2LL8LC2R
      - name: LeGeND Legion!
        tag: VJQ0GJ0
      - name: LeGeND Titan!
        tag: 9PJYVVL2
      - name: LeGeND Rising!
        tag: RY9QJU2
      - name: LeGeND Dynasty!
        tag: 99R2PQVR
      - name: LeGeND Phantom!
        tag: 2CJ88808
      - name: White Plague
        tag: J0CQ9R9
      - name: Dragons Eight 3
        tag: 2ULY20LU
      - name: LeGeND Academy!
        tag: 8QRQQ8RG
      - name: LeGeND Minis!
        tag: 8CL09V0C
```
