### ISSUE TITLE
Clan Family YAML

### ISSUE THREAD

**Issue by TheZeny** [cr-api/cr-api#216]
```yaml
- name: Elementar Bananen
  key: banana
  color: Yellow
  emblem: flag_j_03.png
  sort: trophy
  info:
      logo: comming soon...
      description: >
        Die **Elementar Bananen** Familie besteht aus aktuell 16 Clans
        und ist damit die größte Clash Royale Familie im deutschsprachigen Raum.
        4-5 unserer Clans sind **Top Lokal** und weitere werden folgen.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        **Aktivität** zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität 
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
  clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Krypton Bananen
        tag: 990JPUP2
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Brom Bananen
        tag: 8Y9U8R2G
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Eisen Bananen
        tag: 92RP0LCR
      - name: Lithium Bananen
        tag: 9RYCRCGU
      - name: Dubnium Bananen
        tag: 92JRUYC8
```

**Comment by smlbiobot** [comment]
In the future, please open issue here: 
http://github.com/cr-api/cr-api-ux

```
http://github.com/cr-api/cr-api-ux  <-- this one
http://github.com/cr-api/cr-api     <-- not this one
```

And escape your config like this:

<img width="326" alt="screen shot 2018-01-27 at 10 16 36 pm" src="https://user-images.githubusercontent.com/25040297/35472739-c4444786-03af-11e8-80de-37429cca6f92.png">

**Comment by smlbiobot** [comment]
This is your final config. Please save it for future reference and edit this file instead:

```yaml
  - name: Elementar Bananen
    key: banana
    color: yellow
    emblem: flag_j_03
    sort: trophy
    track: false
    feature: true
    info:
      description: >
        Die **Elementar Bananen** Familie besteht aus aktuell 16 Clans
        und ist damit die größte Clash Royale Familie im deutschsprachigen Raum.
        4-5 unserer Clans sind **Top Lokal** und weitere werden folgen.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        **Aktivität** zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
    clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Krypton Bananen
        tag: 990JPUP2
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Brom Bananen
        tag: 8Y9U8R2G
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Eisen Bananen
        tag: 92RP0LCR
      - name: Lithium Bananen
        tag: 9RYCRCGU
      - name: Dubnium Bananen
        tag: 92JRUYC8
```

i.e. remove all these coming soon stuff
