### ISSUE TITLE
New family Condors

### ISSUE THREAD

**Issue by SOSkr** [cr-api/cr-api#227]
```yaml
  - name: Condors Team
    key: condors
    color: grey
    emblem: flag_j_03
    info:
      description: >
        "Condors Team" is a newly created family, which was founded with 3 leaders of different clans
        
        Our family despite being new we have a lot of experience in different games and with all the desire
        and will to be the best
      social:
        - twitter: http://twitter.com/condorsteam
        - discord: https://discord.gg/ybQ3QwJ
    clans:
      - name: RedCondors
        tag: 9C0JYURP
      - name: BlackCondors
        tag: 9J9GUC0P
      - name: BlueCondors
        tag: 9JY08Q02
```
