### ISSUE TITLE
New Family Dark x

### ISSUE THREAD

**Issue by exQlusive90** [cr-api/cr-api#230]
```
 - name: DarK × Nation
    key: DarK x
    color: grey
    track: false
    emblem:  Skull_06
    feature: true
    info:
      logo: https://imgur.com/a/WbyDK
      description: >

	Die **DarK × Nation** besteht aus **DREI** Clans -> Warriors / Bandits / Fighters!     
	Warriors ist bereits in den TOP 200 DE vertreten, mit dem Ziel die Bandits und Fighters nachzuholen! 
	Was uns auszeichnet? Hohe Aktivität!, Spendenbereitschaft! und jede menge Spaß, außerdem bekommt ihr in allen drei Clans die fertige Clantruhe! 
	Wir sorgen für Abwechslung durch Events und bieten Hilfestellung und Tipps, damit sich jeder unserer Mitglieder verbessern kann!
    social:
        - website: https://dark-elite.com
        - discord: https://discord.gg/UX2jz4Z
        - instagram: https://www.instagram.com/dark_x_nation
        - Youtube: https://www.youtube.com/channel/UCwovV7pC0Ujhwl7aABNAXZA
        - email: mailto:privat@exqlusive.de
    clans:
      - name: DarK × Warriors
        tag: CYU9QVQ
      - name: DarK × Bandits
        tag: URPURJY
      - name: DarK × Fighters
        tag: 2G92L0RY
```

**Comment by smlbiobot** [comment]
@exQlusive90 are you sure that you want to use `darkx` as your key? it needs to be one word and all lose case as it is gonna be used as your URL. Alternatively for now I can just use darkxnation

**Comment by smlbiobot** [comment]
This is your edited config. Please save and use it for future reference:

```yaml
  - name: DarK × Nation
    key: darkxnation
    color: grey
    track: false
    emblem:  Skull_06
    feature: true
    info:
      logo: /static/img/brands/logo/darkxnation.png
      description: >

        Die **DarK × Nation** besteht aus **DREI** Clans -> Warriors / Bandits / Fighters!
        Warriors ist bereits in den TOP 200 DE vertreten, mit dem Ziel die Bandits und Fighters nachzuholen!
        Was uns auszeichnet? Hohe Aktivität!, Spendenbereitschaft! und jede menge Spaß, außerdem bekommt ihr in allen drei Clans die fertige Clantruhe!
        Wir sorgen für Abwechslung durch Events und bieten Hilfestellung und Tipps, damit sich jeder unserer Mitglieder verbessern kann!
      social:
        - website: https://dark-elite.com
        - discord: https://discord.gg/UX2jz4Z
        - instagram: https://www.instagram.com/dark_x_nation
        - Youtube: https://www.youtube.com/channel/UCwovV7pC0Ujhwl7aABNAXZA
        - email: mailto:privat@exqlusive.de
    clans:
      - name: DarK × Warriors
        tag: CYU9QVQ
      - name: DarK × Bandits
        tag: URPURJY
      - name: DarK × Fighters
        tag: 2G92L0RY
```
