### ISSUE TITLE
Banana Family

### ISSUE THREAD

**Issue by TheZeny** [cr-api/cr-api#266]
- name: Banana Family
  key: banana
  color: Yellow
  emblem: flag_j_03.png
  sort: trophy
  info:
      logo: http://fs1.directupload.net/images/180228/tg7b2v3x.png
      description: >
        Willkommen in der Banana Family.
        Eine der größten Clash Royale Familien im deutschsprachigen Raum.
        Mehrere Top Lokal Clans.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        Aktivität zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität 
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
  clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Eisen Bananen
        tag: 92RP0LCR
      - name: Lithium Bananen
        tag: 9RYCRCGU
      - name: Dubnium Bananen
        tag: 92JRUYC8

**Comment by smlbiobot** [comment]
This issue was moved to cr-api/cr-api-ux#25

**Comment by smlbiobot** [comment]
```yaml
  - name: Banana Family
    key: banana
    color: yellow
    emblem: flag_j_03
    sort: trophy
    info:
      logo: /static/img/brands/logo/banana.png
      description: >
        Willkommen in der Banana Family.
        Eine der größten Clash Royale Familien im deutschsprachigen Raum.
        Mehrere Top Lokal Clans.
        Uns gibt es seit dem 19.02.2016, wir sind damit seit den Anfängen im Clash Royale Universum verteten.
        Aktivität zeichnet unsere Clans aus, worunter eine fertige Clan Truhe, sowie hohe Spenden Aktivität
        zu verstehen sind.
      social:
        - discord: https://discord.gg/9rN9qUQ
        - twitch: https://www.twitch.tv/r3dzen
        - youtube: https://www.youtube.com/channel/UC4Vx1Tz36QcqAP8mtEDpKAA
        - website: https://bananenclan.de/
    clans:
      - name: Titan Bananen
        tag: 8Y9LY8CC
      - name: Platin Bananen
        tag: 8GUPGYVY
      - name: Radium Bananen
        tag: 8Q8JRPQV
      - name: Xenon Bananen
        tag: 9YJLCRR0
      - name: Uran Bananen
        tag: 8V09Q88C
      - name: Neon Bananen
        tag: 8PRPP00J
      - name: Aurum Bananen
        tag: 9900ULUC
      - name: Helium Bananen
        tag: 8PRVC990
      - name: Chrom Bananen
        tag: 8CLJQPR0
      - name: Neodym Bananen
        tag: 8QGQGRP0
      - name: Chilli Bananen
        tag: Q9Q8QJQ
      - name: Eisen Bananen
        tag: 92RP0LCR
      - name: Lithium Bananen
        tag: 9RYCRCGU
      - name: Dubnium Bananen
        tag: 92JRUYC8
```

In the future please use spaces instead of tabs. Updated: http://cr-api.com/clan/family/banana/
