### ISSUE TITLE
Registration of Nova l India Family

### ISSUE THREAD

**Issue by NovaRyquaxera** [cr-api/cr-api#268]
name: Nova l India Family
    key: Nova l India 
    color: Purple
    sort: Trophy & Competitive
    emblem:Star_Shine_03 
    logo:/static/img/brands/logo/nova.svg

    info:
      description: >
       Official  Indian Branch of "Nova eSports Organization"

Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.                                              
             Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. Rising Our Nation to Heights #NovaStrong                                    Our Family is 
      social:
        -twitter: http://twitter.com/NovaIndiaTeam
        
      - discord: https://discord.gg/GS8NZ5M
      - email:NovaIndiaTeam@Gmail.com
   
 clans:

-Clan:Nova l India 
Tag:#8GGC990V

-Clan:Nova l India 2 
Tag:#8YRC9VYO

-Clan:Nova l India 3 
Tag:#89QY99GY

-Clan:Nova l IND ApeX
Tag:#92VVUVCL

-Clan:Nova l IND Hype
Tag:#8JYJ9JV9

-Clan:Nova l IND Xtrm
Tag:#9PQY0G8Y

-Clan:Nova l IND DarK
Tag:#8UGL2Y92

-Clan:Nova l IND Gods
Tag:#9GYPGQYG

**Comment by smlbiobot** [comment]
Sort is not competitive. I will sort by trophy

**Comment by smlbiobot** [comment]
Last clan invalid: 

```yaml
     - name: Nova l IND Gods
        tag: 9GYPGQYG
```

**Comment by NovaRyquaxera** [comment]
Name:Nova I IND God's
Tag:8GYPGQYG

**Comment by smlbiobot** [comment]
Here’s your finalized config please save it for your record:

```yaml
  - name: Nova l India Family
    key: nova_india
    color: purple
    sort: trophy
    emblem: Star_Shine_03
    logo: /static/img/brands/logo/nova.svg
    info:
      description: >
        Official  Indian Branch of "Nova eSports Organization"


        Nova l India is organization committed to empowering individuals & Clashers through a supportive team environment. We look for talent in Our Nation and Make them reach thier destiny.


        Our Environment is cultivated and supported through team-based growth strategies and passionate staff that care about player outcomes. Rising Our Nation to Heights #NovaStrong
      social:
        - twitter: http://twitter.com/NovaIndiaTeam
        - discord: https://discord.gg/GS8NZ5M
        - email: mailto:NovaIndiaTeam@Gmail.com
    clans:
      - name: Nova l India
        tag: 8GGC990V
      - name: Nova l India 2
        tag: 8YRC9VY0
      - name: Nova l India 3
        tag: 89QY99GY
      - name: Nova l IND ApeX
        tag: 92VVUVCL
      - name: Nova l IND Hype
        tag: 8JYJ9JV9
      - name: Nova l IND Xtrm
        tag: 9PQY0G8Y
      - name: Nova l IND DarK
        tag: 8UGL2Y92
      - name: Nova l IND Gods
        tag: 8GYPGQYG
```

http://0.0.0.0:8000/clan/family/Nova_india/clans
