### ISSUE TITLE
Include clanChestTier in the clanChest section of the API

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#50]
Refer to [the wiki](http://clashroyale.wikia.com/wiki/Clan_Chest) for tier amounts and all
Percent should also be 100 and not 1.

**Currently**
```
clanChest:
    clanChestCrowns: 1600
    clanChestCrownsPercent: 1
    clanChestCrownsRequired: 1600
```

**Suggested**
```
clanChest:
    clanChestCrowns: 1600
    clanChestCrownsPercent: __100__
    clanChestCrownsRequired: 1600
    __clanChestTier: 10__
```

Firefox nicely formats it for me so I didn't run a HTTP Request
